name: Bug Report
title: "[BUG] "
description: Report a problem you're having
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement of preliminary instructions
      options:
        - label: I have made sure that my problem has not already been addressed.
          required: true
        - label: I am using the latest version of Lunastrap.
          required: true
        - label: I did not answer truthfully to all the above checkboxes.
  - type: input
    id: version
    attributes:
      label: Lunastrap Version
      description: "What version of Lunastrap are you using? Find it in the 'About' section of the Settings"
      placeholder: "v2.3.1"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What problem did you encounter?
      description: Provide a comprehensive description of the problem you're facing. Don't forget to attach any additional resources you may have, such as log files and screenshots.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How do you reproduce the problem?
      description: Include the steps to reproduce the problem from start to finish. Include details such as FastFlags you added and settings you changed.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: log
    attributes:
      label: Bloxstrap Log
      description: If you're getting a Bloxstrap Exception error, upload your log file here. Otherwise, just leave it empty.
      value: "N/A"
      render: text
